# Configuracion base de datos DEV
spring.datasource.url=jdbc:postgresql://localhost:5432/carrito_dev
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# Puerto
server.port=8080